increment_counter:
  description: "Incrementa el contador manualmente."
  fields:
    entity_id:
      description: "ID de la entidad del contador."
      example: "sensor.daily_counter"
      required: true
      selector:
        entity:
          domain: sensor
