name: Check Brands Icons

on:
  pull_request:
  push:
    branches:
      - main
      - develop

jobs:
  check-icons:
    name: Check Brands Icons Presence
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify brands/ha_daily_counter icons
        run: |
          required_files=(
            "brands/ha_daily_counter/icon.png"
            "brands/ha_daily_counter/icon@2x.png"
            "brands/ha_daily_counter/logo.png"
            "brands/ha_daily_counter/logo@2x.png"
          )

          missing_files=0

          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing: $file"
              missing_files=$((missing_files + 1))
            else
              echo "✅ Found: $file"
            fi
          done

          if [ $missing_files -gt 0 ]; then
            echo "❌ ERROR: One or more required icon/logo files are missing in brands/ha_daily_counter."
            exit 1
          fi

      - name: Success message
        if: success()
        run: echo "✅ All required icon/logo files are present."
