name: Continuous Integration

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  schedule:
    - cron: "0 0 * * *"  # Optional: nightly validation

jobs:
  setup:
    name: Common Setup
    runs-on: ubuntu-latest
    outputs:
      python-version: ${{ steps.set-vars.outputs.python-version }}
    steps:
      - name: Set Python version
        id: set-vars
        run: echo "python-version=3.10" >> "$GITHUB_OUTPUT"

  check-icons:
    name: Check Brands Icons
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify required icon/logo files
        run: |
          required_files=(
            "brands/ha_daily_counter/icon.png"
            "brands/ha_daily_counter/icon@2x.png"
            "brands/ha_daily_counter/logo.png"
            "brands/ha_daily_counter/logo@2x.png"
          )

          missing_files=0

          for file in "${required_files[@]}"; do
            if [ ! -f "$file" ]; then
              echo "❌ Missing: $file"
              missing_files=$((missing_files + 1))
            else
              echo "✅ Found: $file"
            fi
          done

          if [ $missing_files -gt 0 ]; then
            echo "❌ ERROR: One or more required icon/logo files are missing in brands/ha_daily_counter."
            exit 1
          fi

  hassfest:
    name: Validate with Hassfest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: home-assistant/actions/hassfest@master

  lint:
    name: Python Lint & Type Check
    runs-on: ubuntu-latest
    env:
      MYPYPATH: .

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install tools
        run: |
          pip install ruff mypy types-setuptools types-pyyaml types-requests

      - name: Run Ruff Linter
        run: ruff check custom_components/ha_daily_counter/

      - name: Run Mypy Type Checker
        run: mypy --config-file mypy.ini
