name: Create GitHub Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Generate GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies (ruff, mypy, etc.)
        run: |
          pip install ruff mypy types-setuptools types-pyyaml types-requests

      - name: Run Makefile Release
        run: make release VERSION=${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
